settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: src
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - html
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
