development:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  dir: database/migrations
  table: migrations