name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    container: circleci/golang:1.15.12-buster-browsers-legacy

    env:
      DB_PROTOCOL: tcp(mysql:3306)
      DB_NAME: echodock
      DB_USER: root
      DB_PASSWORD: pass

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: echodock
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306

    steps:
      # checkout
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2

      # setup database
      - name: setup database
        working-directory: ./src
        run: |
          sql-migrate up

      # build and run test
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    # TODO 暫定無効
    #    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: deploy to prod
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
