name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: cimg/go:1.22.4

    env:
      DB_PROTOCOL: tcp(localhost:3306)
      DB_NAME: echodock
      DB_USER: root
      DB_PASSWORD: pass

    services:
      db:
        image: mysql:8.0 # // TODO 5.7が無くなってそう
        env:
          MYSQL_DATABASE: echodock
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306

    steps:
      # checkout
      - uses: actions/checkout@v2

      # setup libraries
      - name: Setup Libraries
        run: |
          sudo apt-get update
          sudo apt-get install default-mysql-client

      # setup database
      - name: Setup database
        working-directory: ./src
        run: |
          go install github.com/rubenv/sql-migrate/...@latest
          sql-migrate up

      # build and run test
      - name: Build
        working-directory: ./src
        run: go build -v ./...
      - name: Test
        working-directory: ./src
        run: go test -race -v ./...

#  deploy:
#   name: deploy
#    runs-on: ubuntu-latest
#    needs: build-and-test
#    if: github.ref == 'refs/heads/master'
#
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2
#      - name: Deploy to Heroku
#        env:
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
#        run: |
#          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
