name: go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    container: circleci/golang:1.15.12-buster-browsers-legacy

    env:
      DB_PROTOCOL: tcp(localhost:3306)
      DB_NAME: echodock
      DB_USER: root
      DB_PASSWORD: pass

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: echodock
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306

    steps:
      # checkout
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2

      # setup libraries
      - name: Setup Libraries
        run: |
          sudo apt-get update
          sudo apt-get install default-mysql-client

      # setup database
      - name: Setup database
        working-directory: ./src
        run: |
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up

      # build and run test
      - name: Build
        working-directory: ./src
        run: go build -v ./...
      - name: Test
        working-directory: ./src
        run: go test -race -v ./...

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
